package com.google.example.gms.nativeadvancedexample.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.FrameLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import com.google.android.material.appbar.AppBarLayout;
import com.google.android.material.appbar.MaterialToolbar;
import com.google.example.gms.nativeadvancedexample.R;

/**
 * This class is generated by Android Data Binding and provides access to views in the {@code
 * activity_main.xml} layout.
 */
public final class ActivityMainBinding {
  @NonNull private final ConstraintLayout rootView;
  @NonNull public final AppBarLayout appBarLayout;
  @NonNull public final MaterialToolbar toolBar;
  @NonNull public final FrameLayout adFrame;
  @NonNull public final CheckBox startMutedCheckbox;
  @NonNull public final Button refreshButton;
  @NonNull public final TextView videoStatusText;

  private ActivityMainBinding(
      @NonNull ConstraintLayout rootView,
      @NonNull AppBarLayout appBarLayout,
      @NonNull MaterialToolbar toolBar,
      @NonNull FrameLayout adFrame,
      @NonNull CheckBox startMutedCheckbox,
      @NonNull Button refreshButton,
      @NonNull TextView videoStatusText) {
    this.rootView = rootView;
    this.appBarLayout = appBarLayout;
    this.toolBar = toolBar;
    this.adFrame = adFrame;
    this.startMutedCheckbox = startMutedCheckbox;
    this.refreshButton = refreshButton;
    this.videoStatusText = videoStatusText;
  }

  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityMainBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityMainBinding inflate(
      @NonNull LayoutInflater inflater, @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_main, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityMainBinding bind(@NonNull View rootView) {
    int id;
    id = R.id.app_bar_layout;
    AppBarLayout appBarLayout = rootView.findViewById(id);
    if (appBarLayout == null) {
      throw new NullPointerException("Missing required view with ID: " + id);
    }

    id = R.id.toolBar;
    MaterialToolbar toolBar = rootView.findViewById(id);
    if (toolBar == null) {
      throw new NullPointerException("Missing required view with ID: " + id);
    }

    id = R.id.ad_frame;
    FrameLayout adFrame = rootView.findViewById(id);
    if (adFrame == null) {
      throw new NullPointerException("Missing required view with ID: " + id);
    }

    id = R.id.start_muted_checkbox;
    CheckBox startMutedCheckbox = rootView.findViewById(id);
    if (startMutedCheckbox == null) {
      throw new NullPointerException("Missing required view with ID: " + id);
    }

    id = R.id.refresh_button;
    Button refreshButton = rootView.findViewById(id);
    if (refreshButton == null) {
      throw new NullPointerException("Missing required view with ID: " + id);
    }

    id = R.id.video_status_text;
    TextView videoStatusText = rootView.findViewById(id);
    if (videoStatusText == null) {
      throw new NullPointerException("Missing required view with ID: " + id);
    }

    return new ActivityMainBinding(
        (ConstraintLayout) rootView,
        appBarLayout,
        toolBar,
        adFrame,
        startMutedCheckbox,
        refreshButton,
        videoStatusText);
  }
}
