package com.google.example.gms.nativeadvancedexample.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.RatingBar;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import com.google.android.gms.ads.nativead.MediaView;
import com.google.android.gms.ads.nativead.NativeAdView;
import com.google.example.gms.nativeadvancedexample.R;

/**
 * This class is generated by Android Data Binding and provides a binding for the {@code ad_unified}
 * layout.
 */
public final class AdUnifiedBinding {
  @NonNull private final NativeAdView rootView;
  @NonNull public final ImageView adAppIcon;
  @NonNull public final TextView adHeadline;
  @NonNull public final TextView adAdvertiser;
  @NonNull public final RatingBar adStars;
  @NonNull public final TextView adBody;
  @NonNull public final MediaView adMedia;
  @NonNull public final TextView adPrice;
  @NonNull public final TextView adStore;
  @NonNull public final Button adCallToAction;

  private AdUnifiedBinding(
      @NonNull NativeAdView rootView,
      @NonNull ImageView adAppIcon,
      @NonNull TextView adHeadline,
      @NonNull TextView adAdvertiser,
      @NonNull RatingBar adStars,
      @NonNull TextView adBody,
      @NonNull MediaView adMedia,
      @NonNull TextView adPrice,
      @NonNull TextView adStore,
      @NonNull Button adCallToAction) {
    this.rootView = rootView;
    this.adAppIcon = adAppIcon;
    this.adHeadline = adHeadline;
    this.adAdvertiser = adAdvertiser;
    this.adStars = adStars;
    this.adBody = adBody;
    this.adMedia = adMedia;
    this.adPrice = adPrice;
    this.adStore = adStore;
    this.adCallToAction = adCallToAction;
  }

  @NonNull
  public NativeAdView getRoot() {
    return rootView;
  }

  @NonNull
  public static AdUnifiedBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static AdUnifiedBinding inflate(
      @NonNull LayoutInflater inflater, @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.ad_unified, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static AdUnifiedBinding bind(@NonNull View rootView) {
    int id;
    id = R.id.ad_app_icon;
    ImageView adAppIcon = rootView.findViewById(id);
    if (adAppIcon == null) {
      throw new NullPointerException("Missing required view with ID: " + id);
    }

    id = R.id.ad_headline;
    TextView adHeadline = rootView.findViewById(id);
    if (adHeadline == null) {
      throw new NullPointerException("Missing required view with ID: " + id);
    }

    id = R.id.ad_advertiser;
    TextView adAdvertiser = rootView.findViewById(id);
    if (adAdvertiser == null) {
      throw new NullPointerException("Missing required view with ID: " + id);
    }

    id = R.id.ad_stars;
    RatingBar adStars = rootView.findViewById(id);
    if (adStars == null) {
      throw new NullPointerException("Missing required view with ID: " + id);
    }

    id = R.id.ad_body;
    TextView adBody = rootView.findViewById(id);
    if (adBody == null) {
      throw new NullPointerException("Missing required view with ID: " + id);
    }

    id = R.id.ad_media;
    MediaView adMedia = rootView.findViewById(id);
    if (adMedia == null) {
      throw new NullPointerException("Missing required view with ID: " + id);
    }

    id = R.id.ad_price;
    TextView adPrice = rootView.findViewById(id);
    if (adPrice == null) {
      throw new NullPointerException("Missing required view with ID: " + id);
    }

    id = R.id.ad_store;
    TextView adStore = rootView.findViewById(id);
    if (adStore == null) {
      throw new NullPointerException("Missing required view with ID: " + id);
    }

    id = R.id.ad_call_to_action;
    Button adCallToAction = rootView.findViewById(id);
    if (adCallToAction == null) {
      throw new NullPointerException("Missing required view with ID: " + id);
    }

    return new AdUnifiedBinding(
        (NativeAdView) rootView,
        adAppIcon,
        adHeadline,
        adAdvertiser,
        adStars,
        adBody,
        adMedia,
        adPrice,
        adStore,
        adCallToAction);
  }
}
